FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build consumer from cmd/consumer/main.go
RUN go build -o /consumer cmd/consumer/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /consumer .

ENV LEADER_ADDRESS="localhost:8001"
ENV TOPIC="test-logs"

CMD ["./consumer"]