// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: messages.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_PRODUCE       MessageType = 0
	MessageType_DATA          MessageType = 1
	MessageType_CONSUME       MessageType = 2
	MessageType_RESULT        MessageType = 3
	MessageType_REPLICATE     MessageType = 4
	MessageType_HEARTBEAT     MessageType = 5
	MessageType_JOIN          MessageType = 6
	MessageType_JOIN_RESPONSE MessageType = 7
	MessageType_ELECTION      MessageType = 8
	MessageType_NACK          MessageType = 9
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PRODUCE",
		1: "DATA",
		2: "CONSUME",
		3: "RESULT",
		4: "REPLICATE",
		5: "HEARTBEAT",
		6: "JOIN",
		7: "JOIN_RESPONSE",
		8: "ELECTION",
		9: "NACK",
	}
	MessageType_value = map[string]int32{
		"PRODUCE":       0,
		"DATA":          1,
		"CONSUME":       2,
		"RESULT":        3,
		"REPLICATE":     4,
		"HEARTBEAT":     5,
		"JOIN":          6,
		"JOIN_RESPONSE": 7,
		"ELECTION":      8,
		"NACK":          9,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type NodeType int32

const (
	NodeType_LEADER   NodeType = 0
	NodeType_BROKER   NodeType = 1
	NodeType_PRODUCER NodeType = 2
	NodeType_CONSUMER NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "LEADER",
		1: "BROKER",
		2: "PRODUCER",
		3: "CONSUMER",
	}
	NodeType_value = map[string]int32{
		"LEADER":   0,
		"BROKER":   1,
		"PRODUCER": 2,
		"CONSUMER": 3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type ElectionMessage_Phase int32

const (
	ElectionMessage_ANNOUNCE ElectionMessage_Phase = 0
	ElectionMessage_VICTORY  ElectionMessage_Phase = 1
)

// Enum value maps for ElectionMessage_Phase.
var (
	ElectionMessage_Phase_name = map[int32]string{
		0: "ANNOUNCE",
		1: "VICTORY",
	}
	ElectionMessage_Phase_value = map[string]int32{
		"ANNOUNCE": 0,
		"VICTORY":  1,
	}
)

func (x ElectionMessage_Phase) Enum() *ElectionMessage_Phase {
	p := new(ElectionMessage_Phase)
	*p = x
	return p
}

func (x ElectionMessage_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElectionMessage_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[2].Descriptor()
}

func (ElectionMessage_Phase) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[2]
}

func (x ElectionMessage_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElectionMessage_Phase.Descriptor instead.
func (ElectionMessage_Phase) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8, 0}
}

type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,4,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	SenderType    NodeType               `protobuf:"varint,5,opt,name=sender_type,json=senderType,proto3,enum=protocol.NodeType" json:"sender_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PRODUCE
}

func (x *MessageHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageHeader) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageHeader) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *MessageHeader) GetSenderType() NodeType {
	if x != nil {
		return x.SenderType
	}
	return NodeType_LEADER
}

// TCP unicast from Producer to Leader
type ProduceMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ProducerAddress string                 `protobuf:"bytes,3,opt,name=producer_address,json=producerAddress,proto3" json:"producer_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProduceMessage) Reset() {
	*x = ProduceMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceMessage) ProtoMessage() {}

func (x *ProduceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceMessage.ProtoReflect.Descriptor instead.
func (*ProduceMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ProduceMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceMessage) GetProducerAddress() string {
	if x != nil {
		return x.ProducerAddress
	}
	return ""
}

// UDP unicast from Producer to Broker
type DataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DataMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DataMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DataMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// TCP unicast from Consumer to Leader
type ConsumeMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerAddress string                 `protobuf:"bytes,3,opt,name=consumer_address,json=consumerAddress,proto3" json:"consumer_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsumeMessage) Reset() {
	*x = ConsumeMessage{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMessage) ProtoMessage() {}

func (x *ConsumeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMessage.ProtoReflect.Descriptor instead.
func (*ConsumeMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ConsumeMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeMessage) GetConsumerAddress() string {
	if x != nil {
		return x.ConsumerAddress
	}
	return ""
}

// TCP unicast from Broker to Consumer
type ResultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultMessage) Reset() {
	*x = ResultMessage{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMessage) ProtoMessage() {}

func (x *ResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMessage.ProtoReflect.Descriptor instead.
func (*ResultMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ResultMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ResultMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ResultMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResultMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// TCP unicast for Leader to Producer/Consumer
// TCP unicast for Broker to Leader
// UDP multicast for Leader to Brokers
type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

// UDP broadcast from new node to discover cluster
type JoinMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMessage) Reset() {
	*x = JoinMessage{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMessage) ProtoMessage() {}

func (x *JoinMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMessage.ProtoReflect.Descriptor instead.
func (*JoinMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *JoinMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *JoinMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// UDP unicast from Leader to new node
type JoinResponseMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	LeaderAddress   string                 `protobuf:"bytes,3,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	MulticastGroup  string                 `protobuf:"bytes,4,opt,name=multicast_group,json=multicastGroup,proto3" json:"multicast_group,omitempty"`
	BrokerAddresses []string               `protobuf:"bytes,5,rep,name=broker_addresses,json=brokerAddresses,proto3" json:"broker_addresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JoinResponseMessage) Reset() {
	*x = JoinResponseMessage{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponseMessage) ProtoMessage() {}

func (x *JoinResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponseMessage.ProtoReflect.Descriptor instead.
func (*JoinResponseMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *JoinResponseMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *JoinResponseMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResponseMessage) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *JoinResponseMessage) GetMulticastGroup() string {
	if x != nil {
		return x.MulticastGroup
	}
	return ""
}

func (x *JoinResponseMessage) GetBrokerAddresses() []string {
	if x != nil {
		return x.BrokerAddresses
	}
	return nil
}

// TCP unicast from Broker to next Broker in logical ring
type ElectionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	ElectionId    int64                  `protobuf:"varint,3,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
	Phase         ElectionMessage_Phase  `protobuf:"varint,4,opt,name=phase,proto3,enum=protocol.ElectionMessage_Phase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionMessage) Reset() {
	*x = ElectionMessage{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionMessage) ProtoMessage() {}

func (x *ElectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionMessage.ProtoReflect.Descriptor instead.
func (*ElectionMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ElectionMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ElectionMessage) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *ElectionMessage) GetElectionId() int64 {
	if x != nil {
		return x.ElectionId
	}
	return 0
}

func (x *ElectionMessage) GetPhase() ElectionMessage_Phase {
	if x != nil {
		return x.Phase
	}
	return ElectionMessage_ANNOUNCE
}

// UDP multicast from Leader to Brokers, FIFO ordering
type ReplicateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	StateSnapshot []byte                 `protobuf:"bytes,2,opt,name=state_snapshot,json=stateSnapshot,proto3" json:"state_snapshot,omitempty"`
	UpdateType    string                 `protobuf:"bytes,3,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateMessage) Reset() {
	*x = ReplicateMessage{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateMessage) ProtoMessage() {}

func (x *ReplicateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateMessage.ProtoReflect.Descriptor instead.
func (*ReplicateMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicateMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReplicateMessage) GetStateSnapshot() []byte {
	if x != nil {
		return x.StateSnapshot
	}
	return nil
}

func (x *ReplicateMessage) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

// TCP unicast from Broker to specific sender
// UDP multicast from Broker to all (if sender unknown)
type NackMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TargetSenderId string                 `protobuf:"bytes,2,opt,name=target_sender_id,json=targetSenderId,proto3" json:"target_sender_id,omitempty"`
	FromSeq        int64                  `protobuf:"varint,3,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	ToSeq          int64                  `protobuf:"varint,4,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NackMessage) Reset() {
	*x = NackMessage{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackMessage) ProtoMessage() {}

func (x *NackMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackMessage.ProtoReflect.Descriptor instead.
func (*NackMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *NackMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NackMessage) GetTargetSenderId() string {
	if x != nil {
		return x.TargetSenderId
	}
	return ""
}

func (x *NackMessage) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *NackMessage) GetToSeq() int64 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

// BrokerInfo represents a single broker's node state
type BrokerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfo) Reset() {
	*x = BrokerInfo{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfo) ProtoMessage() {}

func (x *BrokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfo.ProtoReflect.Descriptor instead.
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *BrokerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrokerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BrokerInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *BrokerInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

// ProducerInfo represents a producer client (for replication)
type ProducerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerInfo) Reset() {
	*x = ProducerInfo{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerInfo) ProtoMessage() {}

func (x *ProducerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerInfo.ProtoReflect.Descriptor instead.
func (*ProducerInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ProducerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProducerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProducerInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProducerInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

// ConsumerInfo represents a consumer client (for replication)
type ConsumerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Topics        []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"` // Subscribed topics
	LastHeartbeat int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerInfo) Reset() {
	*x = ConsumerInfo{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerInfo) ProtoMessage() {}

func (x *ConsumerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerInfo.ProtoReflect.Descriptor instead.
func (*ConsumerInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *ConsumerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConsumerInfo) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ConsumerInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

// Snapshot of the current registry state (brokers only - legacy)
type RegistrySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       map[string]*BrokerInfo `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeqNum        int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrySnapshot) Reset() {
	*x = RegistrySnapshot{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrySnapshot) ProtoMessage() {}

func (x *RegistrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrySnapshot.ProtoReflect.Descriptor instead.
func (*RegistrySnapshot) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *RegistrySnapshot) GetBrokers() map[string]*BrokerInfo {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *RegistrySnapshot) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

// ClusterStateSnapshot includes all state: brokers + producers + consumers
type ClusterStateSnapshot struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Brokers       map[string]*BrokerInfo   `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Producers     map[string]*ProducerInfo `protobuf:"bytes,2,rep,name=producers,proto3" json:"producers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Consumers     map[string]*ConsumerInfo `protobuf:"bytes,3,rep,name=consumers,proto3" json:"consumers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeqNum        int64                    `protobuf:"varint,4,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"` // Monotonic sequence for FIFO ordering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStateSnapshot) Reset() {
	*x = ClusterStateSnapshot{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStateSnapshot) ProtoMessage() {}

func (x *ClusterStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStateSnapshot.ProtoReflect.Descriptor instead.
func (*ClusterStateSnapshot) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ClusterStateSnapshot) GetBrokers() map[string]*BrokerInfo {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *ClusterStateSnapshot) GetProducers() map[string]*ProducerInfo {
	if x != nil {
		return x.Producers
	}
	return nil
}

func (x *ClusterStateSnapshot) GetConsumers() map[string]*ConsumerInfo {
	if x != nil {
		return x.Consumers
	}
	return nil
}

func (x *ClusterStateSnapshot) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bprotocol\"\xcd\x01\n" +
	"\rMessageHeader\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12!\n" +
	"\fsequence_num\x18\x04 \x01(\x03R\vsequenceNum\x123\n" +
	"\vsender_type\x18\x05 \x01(\x0e2\x12.protocol.NodeTypeR\n" +
	"senderType\"\x82\x01\n" +
	"\x0eProduceMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12)\n" +
	"\x10producer_address\x18\x03 \x01(\tR\x0fproducerAddress\"h\n" +
	"\vDataMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x82\x01\n" +
	"\x0eConsumeMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12)\n" +
	"\x10consumer_address\x18\x03 \x01(\tR\x0fconsumerAddress\"\x82\x01\n" +
	"\rResultMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"C\n" +
	"\x10HeartbeatMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\"X\n" +
	"\vJoinMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xdb\x01\n" +
	"\x13JoinResponseMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12%\n" +
	"\x0eleader_address\x18\x03 \x01(\tR\rleaderAddress\x12'\n" +
	"\x0fmulticast_group\x18\x04 \x01(\tR\x0emulticastGroup\x12)\n" +
	"\x10broker_addresses\x18\x05 \x03(\tR\x0fbrokerAddresses\"\xe1\x01\n" +
	"\x0fElectionMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12\x1f\n" +
	"\velection_id\x18\x03 \x01(\x03R\n" +
	"electionId\x125\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x1f.protocol.ElectionMessage.PhaseR\x05phase\"\"\n" +
	"\x05Phase\x12\f\n" +
	"\bANNOUNCE\x10\x00\x12\v\n" +
	"\aVICTORY\x10\x01\"\x8b\x01\n" +
	"\x10ReplicateMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12%\n" +
	"\x0estate_snapshot\x18\x02 \x01(\fR\rstateSnapshot\x12\x1f\n" +
	"\vupdate_type\x18\x03 \x01(\tR\n" +
	"updateType\"\x9a\x01\n" +
	"\vNackMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.protocol.MessageHeaderR\x06header\x12(\n" +
	"\x10target_sender_id\x18\x02 \x01(\tR\x0etargetSenderId\x12\x19\n" +
	"\bfrom_seq\x18\x03 \x01(\x03R\afromSeq\x12\x15\n" +
	"\x06to_seq\x18\x04 \x01(\x03R\x05toSeq\"z\n" +
	"\n" +
	"BrokerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\"u\n" +
	"\fProducerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\"w\n" +
	"\fConsumerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\"\xc0\x01\n" +
	"\x10RegistrySnapshot\x12A\n" +
	"\abrokers\x18\x01 \x03(\v2'.protocol.RegistrySnapshot.BrokersEntryR\abrokers\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x1aP\n" +
	"\fBrokersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protocol.BrokerInfoR\x05value:\x028\x01\"\x8e\x04\n" +
	"\x14ClusterStateSnapshot\x12E\n" +
	"\abrokers\x18\x01 \x03(\v2+.protocol.ClusterStateSnapshot.BrokersEntryR\abrokers\x12K\n" +
	"\tproducers\x18\x02 \x03(\v2-.protocol.ClusterStateSnapshot.ProducersEntryR\tproducers\x12K\n" +
	"\tconsumers\x18\x03 \x03(\v2-.protocol.ClusterStateSnapshot.ConsumersEntryR\tconsumers\x12\x17\n" +
	"\aseq_num\x18\x04 \x01(\x03R\x06seqNum\x1aP\n" +
	"\fBrokersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protocol.BrokerInfoR\x05value:\x028\x01\x1aT\n" +
	"\x0eProducersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.protocol.ProducerInfoR\x05value:\x028\x01\x1aT\n" +
	"\x0eConsumersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.protocol.ConsumerInfoR\x05value:\x028\x01*\x90\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aPRODUCE\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\v\n" +
	"\aCONSUME\x10\x02\x12\n" +
	"\n" +
	"\x06RESULT\x10\x03\x12\r\n" +
	"\tREPLICATE\x10\x04\x12\r\n" +
	"\tHEARTBEAT\x10\x05\x12\b\n" +
	"\x04JOIN\x10\x06\x12\x11\n" +
	"\rJOIN_RESPONSE\x10\a\x12\f\n" +
	"\bELECTION\x10\b\x12\b\n" +
	"\x04NACK\x10\t*>\n" +
	"\bNodeType\x12\n" +
	"\n" +
	"\x06LEADER\x10\x00\x12\n" +
	"\n" +
	"\x06BROKER\x10\x01\x12\f\n" +
	"\bPRODUCER\x10\x02\x12\f\n" +
	"\bCONSUMER\x10\x03B\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_messages_proto_goTypes = []any{
	(MessageType)(0),             // 0: protocol.MessageType
	(NodeType)(0),                // 1: protocol.NodeType
	(ElectionMessage_Phase)(0),   // 2: protocol.ElectionMessage.Phase
	(*MessageHeader)(nil),        // 3: protocol.MessageHeader
	(*ProduceMessage)(nil),       // 4: protocol.ProduceMessage
	(*DataMessage)(nil),          // 5: protocol.DataMessage
	(*ConsumeMessage)(nil),       // 6: protocol.ConsumeMessage
	(*ResultMessage)(nil),        // 7: protocol.ResultMessage
	(*HeartbeatMessage)(nil),     // 8: protocol.HeartbeatMessage
	(*JoinMessage)(nil),          // 9: protocol.JoinMessage
	(*JoinResponseMessage)(nil),  // 10: protocol.JoinResponseMessage
	(*ElectionMessage)(nil),      // 11: protocol.ElectionMessage
	(*ReplicateMessage)(nil),     // 12: protocol.ReplicateMessage
	(*NackMessage)(nil),          // 13: protocol.NackMessage
	(*BrokerInfo)(nil),           // 14: protocol.BrokerInfo
	(*ProducerInfo)(nil),         // 15: protocol.ProducerInfo
	(*ConsumerInfo)(nil),         // 16: protocol.ConsumerInfo
	(*RegistrySnapshot)(nil),     // 17: protocol.RegistrySnapshot
	(*ClusterStateSnapshot)(nil), // 18: protocol.ClusterStateSnapshot
	nil,                          // 19: protocol.RegistrySnapshot.BrokersEntry
	nil,                          // 20: protocol.ClusterStateSnapshot.BrokersEntry
	nil,                          // 21: protocol.ClusterStateSnapshot.ProducersEntry
	nil,                          // 22: protocol.ClusterStateSnapshot.ConsumersEntry
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: protocol.MessageHeader.type:type_name -> protocol.MessageType
	1,  // 1: protocol.MessageHeader.sender_type:type_name -> protocol.NodeType
	3,  // 2: protocol.ProduceMessage.header:type_name -> protocol.MessageHeader
	3,  // 3: protocol.DataMessage.header:type_name -> protocol.MessageHeader
	3,  // 4: protocol.ConsumeMessage.header:type_name -> protocol.MessageHeader
	3,  // 5: protocol.ResultMessage.header:type_name -> protocol.MessageHeader
	3,  // 6: protocol.HeartbeatMessage.header:type_name -> protocol.MessageHeader
	3,  // 7: protocol.JoinMessage.header:type_name -> protocol.MessageHeader
	3,  // 8: protocol.JoinResponseMessage.header:type_name -> protocol.MessageHeader
	3,  // 9: protocol.ElectionMessage.header:type_name -> protocol.MessageHeader
	2,  // 10: protocol.ElectionMessage.phase:type_name -> protocol.ElectionMessage.Phase
	3,  // 11: protocol.ReplicateMessage.header:type_name -> protocol.MessageHeader
	3,  // 12: protocol.NackMessage.header:type_name -> protocol.MessageHeader
	19, // 13: protocol.RegistrySnapshot.brokers:type_name -> protocol.RegistrySnapshot.BrokersEntry
	20, // 14: protocol.ClusterStateSnapshot.brokers:type_name -> protocol.ClusterStateSnapshot.BrokersEntry
	21, // 15: protocol.ClusterStateSnapshot.producers:type_name -> protocol.ClusterStateSnapshot.ProducersEntry
	22, // 16: protocol.ClusterStateSnapshot.consumers:type_name -> protocol.ClusterStateSnapshot.ConsumersEntry
	14, // 17: protocol.RegistrySnapshot.BrokersEntry.value:type_name -> protocol.BrokerInfo
	14, // 18: protocol.ClusterStateSnapshot.BrokersEntry.value:type_name -> protocol.BrokerInfo
	15, // 19: protocol.ClusterStateSnapshot.ProducersEntry.value:type_name -> protocol.ProducerInfo
	16, // 20: protocol.ClusterStateSnapshot.ConsumersEntry.value:type_name -> protocol.ConsumerInfo
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
